"""create user table

Revision ID: 5fd216b81bc2
Revises: c0095648e573
Create Date: 2022-11-01 23:28:58.729414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd216b81bc2'
down_revision = 'c0095648e573'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
