"""create user table

Revision ID: c1677d0c261c
Revises: 5fd216b81bc2
Create Date: 2022-11-01 23:29:07.218349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1677d0c261c'
down_revision = '5fd216b81bc2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('last_name', sa.String(length=150), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.drop_index('ix_users2_id', table_name='users2')
    op.drop_table('users2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users2',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_users2_id', 'users2', ['id'], unique=False)
    op.drop_table('users')
    # ### end Alembic commands ###
